### ISSUE TITLE
Wrong number of arguments for time_entry.rb

### ISSUE THREAD

**Issue by shankie-codes** [semanticdreamer/mite-api-csv-import#1]
I'm new to Ruby, so please bear with me. 

When I try to import my CSV file, the first row imports successfully. On the second row (regardless of the content of that second row, import fails and generates the following errors in Terminal:

```
-------------------------------------------
          mite. API CSV Import            
-------------------------------------------
 - import to account 'papercut'.
/Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/mite-rb-0.4.4/lib/mite/time_entry.rb:40:in `load': wrong number of arguments (2 for 1) (ArgumentError)
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/base.rb:1370:in `load_attributes_from_response'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/base.rb:1362:in `block in create'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/base.rb:1360:in `tap'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/base.rb:1360:in `create'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/observing.rb:19:in `create_with_notifications'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/base.rb:1155:in `save'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/validations.rb:79:in `save_with_validation'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/observing.rb:19:in `save_with_notifications'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/base.rb:746:in `block in create'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/base.rb:746:in `tap'
    from /Users/shankie/.rvm/gems/ruby-1.9.2-p320/gems/activeresource-3.2.8/lib/active_resource/base.rb:746:in `create'
    from importer.rb:90:in `block in <main>'
    from /Users/shankie/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1768:in `each'
    from /Users/shankie/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1202:in `block in foreach'
    from /Users/shankie/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1340:in `open'
    from /Users/shankie/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/csv.rb:1201:in `foreach'
    from importer.rb:40:in `<main>'
```

I'm not sure if this is a genuine issue or me being a newbie. Any thoughts, anyone? Thanks in advance

Mac OS X 10.8.2, Ruby 1.9.2

**Comment by semanticdreamer** [comment]
You're not using Bundler to manage ruby gem dependencies, right? But you should :)

As I can tell from the stack trace you posted you're using activeresource in version 3.2.8.
Unfort. there is a dependency for mite-rb (the official ruby library for interacting with the RESTful mite.api) requiring  activeresource in version 2.3.14 (see Gemfile).

I'd recommend to use Bundler (http://gembundler.com), see "Setup" section of project README.

Feel free to reopen issue if this doesn't solve your issue.

**Comment by shankie-codes** [comment]
That was exactly it. It didn't even occur to me to read the mite-rb readme files rather than just the importer.rb ones.

Thanks semanticdreamer, you're a legend. Saved me loads of time. Hopefully I can help you one day too.
